
public class HardBoss extends Boss {
	
	public HardBoss() {
		setHp(90);
	}
	questions.add(new Question("Which of the following are valid characters for a numeric literal constant(C++)? ", "None of the above", "a comma", "a dollar sign ($)", "a percent sign (%)");
	questions.add(new Question("The symbols used in an assembly language are ", "Mnemonics", "Codes", "Assembler", "None of the above");
	questions.add(new Question("A function that changes the state of the cout object is called a(n) _____ ", "manipulator", "member", "adjuster", "operator");
	questions.add(new Question("4.What was originally called the 'imitation game' by its creator? ", "The Logic Theorist", "The Turing Test", "LISP", "Cybernetics");
	questions.add(new Question("Weak AI is ", "the study of mental faculties through the use of mental models implemented on a computer.", "the embodiment of human intellectual capabilities within a computer.", "a set of computer programs that produce output that would be considered to reflect intelligence if it were generated by humans.", "None of the above");
	questions.add(new Question("A top-to- bottom relationship among the items in a database is established by a ", "Hierarchical schema", "Network schema", "Relational schema", "None of the above");
	questions.add(new Question("The PROJECT command (SQL) will create new table that has ", "None of the above", "more fields than the original table", "more rows than the original table", "all the fields of master table");
	questions.add(new Question("In a _____ a parent record type can be linked to one or more 'child' record types, but a child record type can have only one parent. ", "Hierarchical database", "Network database", "Relational database", "None of the above");
	questions.add(new Question("Visual clues that are helpful in computer vision include: ", "colour and motion & depth and texture ", "colour and motion", "depth and texture", "height and weight");
	questions.add(new Question("Which of the following is not a relational database? ", "Reflex", "dBASE IV", "4th Dimension", "FoxPro");
	questions.add(new Question("Which interface does java.util.Hashtable implement? ", "Java.util.Map", "Java.util.List", "Java.util.HashTable", "Java.util.Collection");
	questions.add(new Question("Which of the following are Java reserved words? 1. run, 2. import, 3. default, 4. implement ", "2 and 3", "1 and 2", "3 and 4", "2 and 4");
	questions.add(new Question("How many bytes are occupied by near, far and huge pointers (DOS)? ", "near=4 far=8 huge=8", "near=2 far=4 huge=4", "near=2 far=4 huge=8", "near=4 far=4 huge=8");
	questions.add(new Question("An abstract class is which of the following? ", "A class that has no direct instances, but whose descendants may have direct instances.", "A class that has direct instances, but whose descendants may have direct instances.", "A class that has direct instances, but whose descendants may not have direct instances.", "A class that has no direct instances, but whose descendants may not have direct instances");
}
