//Test the Question Class
public class QuestionObjects {

	public static void main(String[] args) {
		//Easy questions
		Question q = new Question("A language which is close to that used within the computer is ", "Low-level language", "High-level language", "Assembly language", "All of the above" , "None of the above");
		Question q2 = new Question("The first generation of computers available was based on the bit micro processors. ", "8", "4", "16", "64", "None of the above");
		Question q3 = new Question("The step-by- step instructions that solve a problem are called _____. ", "An algorithm", "A list", "A plan", "A sequential structure", "None of the above");
		Question q4 = new Question("The operator used to get value at address stored in a pointer variable is ", "*", "&", "&&", "||");
		
		//Medium questions
		Question q5 = new Question("A single packet on a data link is known as ", "Frame", "Path", "Block", "Group", "None of the above");
		Question q6 = new Question("ASCII stands for ", "American standard code for information interchange", "All purpose scientific code for information interchange", "American security code for information interchange", "American Scientific code for information interchange", "None of the above");
		Question q7 = new Question("Which language was devised by Dr. Seymour Aubrey Papert? ", "LOGO", "APL", "COBOL", "FORTRAN", "None of the above");
		Question q8 = new Question("A memory that does not change its contents without external causes is known as ", "Static memory", "Dynamic memory", "RAM", "EEPROM", "None of the above");
		Question q9 = new Question("The organization and interconnection of the various components of a computer system is ", "Architecture", "Networks", "Graphics", "Designing", "None of the above");
		Question q10 = new Question("A default catch block catches ", "any thrown object that has not been caught by an earlier catch block", "all thrown objects", "no thrown objects", "all thrown objects that have been caught by an earlier catch block");
		Question q11 = new Question("In SQL, which command is used to make permanent changes made by statements issue since the beginning of a transaction? ", "COMMIT", "PACK", "ZIP", "SAVE", "None of the above");
		Question q12 = new Question("In SQL, which command(s) is(are) used to enable/disable a database trigger? ", "ALTER TRIGGER", "MODIFY USER", "CHANGE USER", "All of the above", "None of the above");
		Question q13 = new Question("In which statements, does a 'continue' statements cause the control to go directly to the test condition and then continue the looping process? ", "'while' and 'do-while'", "'for' and 'while'", "'while' and 'if-else'", "'do-while' and 'if-else'", "None of the above");
		Question q14 = new Question("Who is considered to be the 'father' of artificial intelligence? ", "John McCarthy", "Fisher Ada", "Allen Newell", "Alan Turning", "None of the above");
		Question q15 = new Question("A CASE SQL statement is which of the following? ", "A way to establish an IF-THEN- ELSE in SQL.", "A way to establish a loop in SQL.", "A way to establish a data definition in SQL.", "All of the above.");
		Question q16 = new Question("Which of the following mechanisms is/are provided by an Object Oriented Language to implement Object Oriented Model? ", "All of the Above", "Encapsulation", "Inheritance", "Polymorphism", "None of the above");
		
		//Hard questions
		Question q17 = new Question("Which of the following are valid characters for a numeric literal constant(C++)? ", "None of the above", "a comma", "a dollar sign ($)", "a percent sign (%)", "a space");
		Question q18 = new Question("The symbols used in an assembly language are ", "Mnemonics", "Codes", "Assembler", "All of the above", "None of the above");
		Question q19 = new Question("A function that changes the state of the cout object is called a(n) _____ ", "manipulator", "member", "adjuster", "operator");
		Question q20 = new Question("4.What was originally called the 'imitation game' by its creator? ", "The Logic Theorist", "The Turing Test", "LISP", "Cybernetics", "None of the above");
		Question q21 = new Question("Weak AI is ", "the study of mental faculties through the use of mental models implemented on a computer.", "the embodiment of human intellectual capabilities within a computer.", "a set of computer programs that produce output that would be considered to reflect intelligence if it were generated by humans.", "All of the above", "None of the above");
		Question q22 = new Question("A top-to- bottom relationship among the items in a database is established by a ", "Hierarchical schema", "Network schema", "Relational schema", "All of the above", "None of the above");
		Question q23 = new Question("The PROJECT command (SQL) will create new table that has ", "None of the above", "more fields than the original table", "more rows than the original table", "all the fields of master table");
		Question q24 = new Question("In a _____ a parent record type can be linked to one or more 'child' record types, but a child record type can have only one parent. ", "Hierarchical database", "Network database", "Relational database", "Distributed database", "None of the above");
		Question q25 = new Question("Visual clues that are helpful in computer vision include: ", "colour and motion & depth and texture ", "colour and motion", "depth and texture", "height and weight", "None of the above");
		Question q26 = new Question("Which of the following is not a relational database? ", "Reflex", "dBASE IV", "4th Dimension", "FoxPro", "None of the above");
		Question q27 = new Question("Which interface does java.util.Hashtable implement? ", "Java.util.Map", "Java.util.List", "Java.util.HashTable", "Java.util.Collection");
		Question q28 = new Question("Which of the following are Java reserved words? 1. run, 2. import, 3. default, 4. implement ", "2 and 3", "1 and 2", "3 and 4", "2 and 4");
		Question q29 = new Question("How many bytes are occupied by near, far and huge pointers (DOS)? ", "near=4 far=8 huge=8", "near=2 far=4 huge=4", "near=2 far=4 huge=8", "near=4 far=4 huge=8");
		Question q30 = new Question("An abstract class is which of the following? ", "A class that has no direct instances, but whose descendants may have direct instances.", "A class that has direct instances, but whose descendants may have direct instances.", "A class that has direct instances, but whose descendants may not have direct instances.", "A class that has no direct instances, but whose descendants may not have direct instances");
	}

}